### PR TITLE
Properly implement low battery notification service

### LINKED ISSUE #575: Low battery notification is not sent
**Describe the bug**
The low battery notification is not sent when battery drops bellow the limit

**To Reproduce**
1. Enable low battery notification
image
2. Wait for the battery to drop under that level
3. Notice no notification is sent

There are quite bad reproduction steps, but if needed I can gather and post more information :)

**Expected behavior**
Notification is sent when battery drops under threshold.

**Screenshots**
N/A

**Desktop:**
 - Distribution: Arch Linux
 - Window Manager/Desktop Environment: Hyprland

**Additional context**
This happened before ags v2 migration, but I waited to report it until the migration was complete. It unfortunately still happens

### PR DESCRIPTION
**Pull request by davfsa**
The original implementation had multiple issues:
1. The service itself would never trigger as it listened to be notified of the wrong variable. Should have been `percentage` not `percent`
2. `.percentage` is reported as a double between 0 and 1, so setting the threshold to a percentage representation of the threshold (20 for example) would never trigger it
3. Strict comparison of doubles would never work as the battery percentage will always be way more precise than 2 decimal points
4. The replacement of the magic value `$POWER_LEVEL` did not work at all

Instead I opted for an implementation that checks for the values bellow the threshold and send the notification if bellow that value, resetting this when the battery is reported as charging

Closes #575

### CODE REVIEW

File: src/lib/behaviors/batteryWarning.ts [hunk 1]
```diff
@@ -3,22 +3,45 @@ import icons from '../icons/icons';
 import { Notify } from '../utils';
 
 export function warnOnLowBattery(): void {
-    batteryService.connect('notify::percent', () => {
+    var sentLowNotification = false;
+    var sentHalfLowNotification = false;
```
Comment (Jas-SinghFSU) [inline src/lib/behaviors/batteryWarning.ts:7]:
```suggestion
    let sentHalfLowNotification = false;
```

File: src/lib/behaviors/batteryWarning.ts [hunk 2]
```diff
@@ -3,22 +3,45 @@ import icons from '../icons/icons';
...
         }
 
+        // batteryService.percentage will be a double in between 0 and 1, so we multiply it by 100 to convert it to the percentage
+        const batteryPercentage = Math.floor(batteryService.percentage * 100);
         const lowThreshold = lowBatteryThreshold.get();
 
-        if (batteryService.percentage === lowThreshold || batteryService.percentage === lowThreshold / 2) {
+        // To avoid double notifications, we check each of the thresholds and set the correct `sentNotification`, but then
+        // combine them into one notification only
+        var sendNotification = false;
```
Comment (Jas-SinghFSU) [inline src/lib/behaviors/batteryWarning.ts:31]:
```suggestion
        let sendNotification = false;
```

**Comment by Jas-SinghFSU** [comment]
Ty :heart:
